version: "3.8"

services:
  todoback:
    image: todobackend
    ports: 
      - 3001:3001
    restart: always

  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    restart: always

  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todoback
      - todofront
    restart: always
